#!/bin/bash
cmake -DCMAKE_TOOLCHAIN_FILE=$(readlink -f $ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake) \
-DANDROID_ABI=$ANDROID_ABI -DANDROID_PLATFORM=$ANDROID_PLATFORM \
--install-prefix=$PREFIX -GNinja . "$@"

ninja install