#!/bin/bash

if [ -d "./_build" ]; then 
    recon="--reconfigure" 
fi

meson _build --pkg-config-path="$PKG_CONFIG_PATH" \
    --cross-file ../meson-crossfiles/aarch64.ini \
    --prefix=$PREFIX \
    $recon "$@" 

ninja install -C _build